# Generated by Django 4.0.2 on 2022-07-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cast',
            new_name='disable',
        ),
    ]
