# Generated by Django 4.0.2 on 2022-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_rename_cast_student_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_passing',
            field=models.CharField(max_length=4),
        ),
    ]
