# Generated by Django 4.0.2 on 2022-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_student_year_of_passing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_passing',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearly_income',
            field=models.IntegerField(max_length=50),
        ),
    ]
